language: node_js
sudo: required
node_js: stable
install:
  - npm install
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - xvfb-run npm run test